baseURL = 'http://xtzi9859.github.io/'
canonifyurls = true
DefaultContentLanguage='ja'
languageCode = 'ja-JP'
title = 'My New Hugo Site'
theme = 'Mainroad'
publishDir = 'docs'
[Author]
	name = 'NAO'
	bio = 'いいよこいよ!'
	
[Params]
	description = 'aaa'
	copyright = '4545'
	toc = true
	mainSections = ["post"]
[Params.logo]
	title = 'title'
